### ISSUE TITLE
AttributeError: module 'tmap' has no attribute 'layout_from_edge_list' on WSL2

### ISSUE THREAD

**Issue by brendaferrari** [reymond-group/tmap#21]
I'm trying to run the "Laying out a Simple Graph" script on WSL2 and I'm getting this problem: 

```
Traceback (most recent call last):
  File "tmap.py", line 40, in <module>
    main()
  File "tmap.py", line 18, in main
    x, y, s, t, _ = tm.layout_from_edge_list(
AttributeError: module 'tmap' has no attribute 'layout_from_edge_list'
```

I saw that a person had this issue running on MAC OS and I would like to know if the module has been tested on WSL2 environment or If I am doing something wrong to run the module.

**Comment by Lerbytech** [comment]
I think that rebuilding from scratch is best option
